%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    /home/rghunter/OpticalQuad/OpticalFlowCV/data/performance_data.csv
%    Worksheet: performance_data
%
% To extend the code to different selected data or a different spreadsheet,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2012/10/05 14:58:31

performance_data = importdata('/home/rghunter/OpticalQuad/OpticalFlowCV/data/performance_data.csv');
mean_perf = mean(performance_data);
total = sum(mean_perf');
norm_perf = mean_perf/total;
bar(norm_perf)
set(gca,'XTickLabel',{'colorspace','unDistort','SURF','FREAK','Match','Distance Thresh'})